### PR TITLE
runner: treat missing pcap as condition to 'skip'

### PR DESCRIPTION
**Pull request by victorjulien**
This allows disabling of tests by renaming the pcap file to <pcap>.disabled
or similar.

### CODE REVIEW

**Comment by jasonish** [comment]
Merged. Thanks!

**Comment by jasonish** [comment]
Forgot to close.

**Comment by victorjulien** [comment]
Think this issue was reintroduced by last nights changes though.

I need:
```
-        if pcaps:
-            args += ["-r", pcaps[0]]
+        if not pcaps:
+            raise UnsatisfiedRequirementError("No pcap file found")
+        args += ["-r", pcaps[0]]
```
To fix it.

**Comment by jasonish** [comment]
On Wed, Jan 17, 2018 at 6:40 AM, Victor Julien <notifications@github.com>
wrote:

> Think this issue was reintroduced by last nights changes though.
>
> I need:
>
> -        if pcaps:
> -            args += ["-r", pcaps[0]]
> +        if not pcaps:
> +            raise UnsatisfiedRequirementError("No pcap file found")
> +        args += ["-r", pcaps[0]]
>
> To fix it.
>

Oops, I refactored that, but it only ran if there was a test.yaml. Should
be fixed now.

**Comment by victorjulien** [comment]
Confirmed fixed, thanks.

**Pull request closed without merging**
